### ISSUE TITLE
range selector not respecting inverted y axis

### ISSUE THREAD

**Issue by carmex** [danvk/dygraphs#601] opened 2015-04-22 16:58 UTC
When specifying an inverted y axis via valueRange, the range selector just displays the data in non-inverted fashion. It still works fine otherwise so this is a display-only bug.

Here's an example:
http://jsfiddle.net/oh33fm0z/5/

Thanks!

**Comment by danvk** [comment] 2015-04-27 14:35
Dupe of #375

**Closed by danvk** 2015-04-27 14:35 UTC
