### ISSUE TITLE
V2.2.1 not a drop in replacement for V2.1.0. 2nd series drawn wrong in my case

### ISSUE THREAD

**Issue by mdrmdrmdr** [danvk/dygraphs#1045] opened 2024-01-21 11:17 UTC
I'm using Dygraphs V2.1.0 since years for visualization of consumption of gas, electrical energy and water. Recently I discovered that V2.2.1 is available since a while and I tried a drop-in replacement of my V2.1.0. Unfortunately it displays my 2nd series (daily consumption) quite different. While 1st series (cumulative consumption totals) is fine. I have no clue where to start looking for the error, as with V2.1.0 it works perfectly fine. There are no JS errors seen in  the browsers console (same for FF and Chrome).

Any hints very welcome.

![Dygraphs_2 1 0](https://github.com/danvk/dygraphs/assets/16529884/f11432ed-c883-4629-94f6-da9bcf519f98)
![Dygraphs_2 2 1](https://github.com/danvk/dygraphs/assets/16529884/6271b187-af0f-4928-853c-13d8a301f2db)

**Comment by mirabilos** [comment] 2024-01-21 18:11
Okaaaay, this is not so nice, but I don’t have an idea outright.

Looking at the screenshots, your y2 axis has a different scale… just to clarify, y1 is green and y2 is red, correct?

You could try what happens if you force the y2 scale to a known range.

Other than that, I’m afraid, it’s merely guesswork. Can you provide the HTML+JS and a batch of values (CSV/JSON/…) so others can have a direct look at it? (Don’t worry about the German, at least I get that.)

**Comment by mdrmdrmdr** [comment] 2024-01-22 21:59
Ok, tomorrow I'll prepare a standalone easy to use version of my close to 1.000 lines JS code...

**Comment by mirabilos** [comment] 2024-01-22 23:10
mdrmdrmdr dixit:

>Ok, tomorrow I'll prepare a standalone easy to use version of my close
>to 1.000 lines JS code...

Good luck! (I don’t envy having to do this…)

bye,
//mirabilos
-- 
„Cool, /usr/share/doc/mksh/examples/uhr.gz ist ja ein Grund,
mksh auf jedem System zu installieren.“
	-- XTaran auf der OpenRheinRuhr, ganz begeistert
(EN: “[…]uhr.gz is a reason to install mksh on every system.”)

**Comment by mdrmdrmdr** [comment] 2024-01-23 22:40
Attached is my application. Just extract and save all files from the archive in the root of a web server and call either `usage_2.1.0.html` or `usage_2.2.1.html`.
In the meanwhile, I'm pretty sure that the problem is in the area of changing `Rolling Averages` / `rollPeriod`. In my code (**usage.js**), the rolling period is set in function `updateRollPeriod` (triggered by the 2 input fields `Wert` and `Delta`). This works fine for 2.1.0 but all rollPeriods for 2.2.1 seems to always stay at 1, regardless what values are sent to `Dygraphs`.

[Usage.zip](https://github.com/danvk/dygraphs/files/14030441/Usage.zip)

**Comment by mdrmdrmdr** [comment] 2024-01-24 22:24
I think I found a (the?) solution which i already applied to my V2.1.0. I do not remember anymore from where I got this solution:

in `Dygraph.prototype.predraw_ = function () {`

comment out this:

```
  /**
  this.rolledSeries_ = [null]; // x-axis is the first series and it's special
  for (var i = 1; i < this.numColumns(); i++) {
    // var logScale = this.attr_('logscale', i); // TODO(klausw): this looks wrong // konigsberg thinks so too.
    var series = this.dataHandler_.extractSeries(this.rawData_, i, this.attributes_);
    if (this.rollPeriod_ > 1) {
      series = this.dataHandler_.rollingAverage(series, this.rollPeriod_, this.attributes_, i);
    }
    this.rolledSeries_.push(series);
  }
  **/
```

and add this:

```
  var seriesName = this.getLabels();
  this.rolledSeries_ = [null]; // x-axis is the first series and it's special
  for (var i = 1; i < this.numColumns(); i++) {
    // var logScale = this.attr_('logscale', i); // TODO(klausw): this looks wrong // konigsberg thinks so too.
    var series = this.dataHandler_.extractSeries(this.rawData_, i, this.attributes_);
    var rollPeriod = this.getOption('rollPeriod', seriesName[i]);
    if (rollPeriod > 1) {
    	series = this.dataHandler_.rollingAverage(series, rollPeriod, this.attributes_);
    }
    this.rolledSeries_.push(series);
  }
```

With this change, V2.2.1 "seems" to behave as V2.1.0.

**Comment by mirabilos** [comment] 2024-01-24 23:06
mdrmdrmdr dixit:

>I think I found a (the?) solution which i already applied to my V2.1.0.

With this, do you mean your code already didn’t work on an
unmodified 2.1.0?

>I do not remember anymore from where I got this solution:

Ouch. That would have been interesting.

So something like this, diff-wise:

>+ var seriesName = this.getLabels();
>  this.rolledSeries_ = [null]; // x-axis is the first series and it's special
>  for (var i = 1; i < this.numColumns(); i++) {
>    // var logScale = this.attr_('logscale', i); // TODO(klausw): this looks wrong // konigsberg thinks so too.
>    var series = this.dataHandler_.extractSeries(this.rawData_, i, this.attributes_);
>-   if (this.rollPeriod_ > 1) {
>+   var rollPeriod = this.getOption('rollPeriod', seriesName[i]);
>+   if (rollPeriod > 1) {
>-     series = this.dataHandler_.rollingAverage(series, this.rollPeriod_, this.attributes_, i);
>+     series = this.dataHandler_.rollingAverage(series, rollPeriod, this.attributes_);
>    }
>    this.rolledSeries_.push(series);
>  }

From this, I can see:

• you get the rollPeriod from somewhere else
  ⇒ is the this.rollPeriod_ not correct?

• you removed the last ‘i’ argument in the call to
  this.dataHandler_.rollingAverage
  ⇒ is this intentional? it looks to me more like
    it’s caused by an old patch?

Can you verify whether…

>+     series = this.dataHandler_.rollingAverage(series, rollPeriod, this.attributes_, i);

… also works?

Thanks,
//mirabilos
-- 
Infrastrukturexperte • Qvest Digital AG
Am Dickobskreuz 10, D-53121 Bonn • https://www.qvest-digital.com/
Telephon +49 228 54881-393 • Fax: +49 228 54881-235
HRB AG Bonn 18196 • USt-ID (VAT): DE274355441
Vorstand: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg
Vorsitzender Aufsichtsrat: Peter Nöthen

**Comment by mdrmdrmdr** [comment] 2024-01-25 08:47
Yes, as far as I can remember the "roll period per series" never worked and never was in Dygraphs.
See here: https://github.com/danvk/dygraphs/pull/811. I even asked there in January 2018 when it will get added (last comment), but never got an answer.

**Comment by mirabilos** [comment] 2024-01-25 22:46
OK, so this is basically not a bug but a request for #811 to be merged.

danvk reviewed #811 quite a bit, and there seem to be no performance concerns (removal of the `rollPeriod_` variable and perhaps the function left), so with a bit more development work that seems doable.

Unfortunately, the project which allowed me to spend some dayjob time on this is currently stalled, so I can’t promise anything timely.

As this is already tracked in #811 *and* you stated there that you currently add it to each release manually, I’ll close here.

**Closed by mirabilos** 2024-01-25 22:46 UTC
