### ISSUE TITLE
Resize is slow

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#425] opened 2014-10-20 22:44 UTC
_From [soos.m...@gmail.com](https://code.google.com/u/104196047207946491571/) on February 10, 2014 15:12:01_

I have a lot of graphs, and a LOT of data. Takes about 2-3s to draw the graphs. TThey are auto-resizing -- if the user changes the size of the browser window, the graphs get re-drawn. However, this is exceedingly slow, like +30s, not 2-3s. Just load into a horizontally ~900px browser, and expand to horizontally 1200px: http://www.msoos.org/private/sat2/ Behavior is the same for both Chrome and Firefox, new versions. Dygraph.prototype.resize() is running most of the time. I think it is trying to re-draw while resizing, and that just kills the performance, it probably is trying to draw it >20x. Would be nice to have a way of telling the redraw system to only try to redraw once every 5s so the user will have to wait a bit, but get a system that is unresponsive for only the duration of 1 draw.

_Original issue: http://code.google.com/p/dygraphs/issues/detail?id=508_

**Comment by kbaggott** [comment] 2016-02-25 13:57
@danvk is this still an issue? I can't reproduce it on the resize page, looking to close it if not, as it's pretty old.

**Comment by danvk** [comment] 2016-02-25 23:48
Feel free to close. Thanks for going through these issues! If you need motivation, it's always fun to see this chart drop: http://github-issue-tracker.herokuapp.com/danvk/dygraphs

**Comment by kbaggott** [comment] 2016-02-26 01:25
Closing due to inactivity

**Closed by kbaggott** 2016-02-26 01:25 UTC
Labels: bug, imported, Performance
