### ISSUE TITLE
"connectSeparatedPoints:true" produces "undefined" in legend for missing values. 

### ISSUE THREAD

**Issue by noamparn** [danvk/dygraphs#853] opened 2017-03-27 00:30 UTC
The example "Connect-Separated" displays this problem very clearly:
http://dygraphs.com/tests/connect-separated.html

If you click the toggles at the bottom to set them to "true," you get "undefined" for any point that is missing data in the graph. 

I am seeing this on my own pages using the 2.0.0 version (same as here). However, my own pages work fine if I go back to the 1.1.1 code.

**Comment by noamparn** [comment] 2017-03-27 02:18
Setting "connectSeparatedPoints" to "true" will cause this problem to show up.

**Comment by danvk** [comment] 2017-03-29 01:46
Repro: https://jsfiddle.net/eM2Mg/9541/

**Comment by noamparn** [comment] 2017-04-20 13:15
The JSFiddle (above) shows the problem. Line 3 of the data has a missing (null) "Z" data point. Moving the mouse over the graph at that point shows "undefined" in the legend for the "Z" value. Previously, it just wouldn't display anything for a null value.

**Comment by noamparn** [comment] 2017-05-25 00:21
I reported this bug almost 2 months ago, but there has been no acknowledgement of the bug yet.

**Comment by danvk** [comment] 2017-05-26 02:45
The bug has been [acknowledged][1]. There's generally no SLA for volunteer-driven open source projects. 

[1]: https://github.com/danvk/dygraphs/issues/853#issuecomment-289957150

**Comment by dandigregorio** [comment] 2018-02-14 10:40
I've stumbled into this problem too. I've realized that the problem is present only when the datasource is a js obj, not in case the graph is populated via CSV.

Any news about a workaround?

**Comment by ALobpreis** [comment] 2019-02-28 14:47
> I've stumbled into this problem too. I've realized that the problem is present only when the datasource is a js obj, not in case the graph is populated via CSV.

This is happening to me but with a CSV source as well. For example:
`2019-02-21 21:34:29,,99.62,
2019-02-21 22:24:28,87.49,,`

**Comment by mkreim** [comment] 2019-05-03 11:07
I had the same problem. I could work around it by filling up my input data to not contain any `null` values. I did this by filling up the missing values with the last "known" value, i.e. creating a stair function but interpolation will work as well. However, I am not plotting the original data anymore but this was fine for the project.

**Comment by Abroxa** [comment] 2019-08-26 13:37
I just also had the exact same problem and couldn't workaround it. A fix would be very welcome. Why not just calling valueFormatter in any case, maybe with a separate option 'callValueFormatterForUndefinedValues' defaulting to false for backwards compatibility?

**Comment by mkreim** [comment] 2019-08-26 13:38
*** English version below ***

Sehr geehrte Damen und Herren,

ich bin bis einschließlich zum 11. September 2019 nur eingeschränkt per E-Mail und Telefon erreichbar. Ihre E-Mails werden nicht weiter geleitet. In dringenden Fällen kontaktieren Sie bitte  meinen Kollegen Daniel Rech (dr@netsyno.com , +491626477725).

Vielen Dank für Ihr Verständnis.

Mit freundlichen Grüßen

Michael Kreim

*** English ***

Dear Sir or Madam,

Thank you for your message.

I am currently out of the office and will be back on 12th September 2019. Your e-mail will not be forwarded. In urgent cases please contact my colleague Daniel Rech (dr@netsyno.com , +491626477725).
Thank you very much.

Kind regards,

Michael Kreim

**Comment by ALobpreis** [comment] 2019-10-25 17:03
Based on what CameronSinclair84 said, I did some test and indeed that function is what renders the whole legend line, instead of just one series. So if you overwrite it, you will have to include several lines of code to achieve the exact same default output.
I took a look at the code in **http://dygraphs.com/2.1.0/dygraph.js** and found where the problem lies. In the `Legend.defaultFormatter` function, near the end, you have to replace ` + series.yHTML + ` with ` + (series.yHTML || "") + `.
So you either update the source code or overwrite that function in `options.legendFormatter`.

**Comment by CameronSinclair84** [comment] 2019-10-28 12:50
What I mean is you can pass in a callback function as an option in the options block to handle this.

**Comment by ALobpreis** [comment] 2019-10-28 18:07
Well, I was also talking about specifying a function in `options.legendFormatter` to override the default one. I like your approach with the lines in the legend. Here is my simplified approach:

`      // options go here. See http://dygraphs.com/options.html
    {
      legend: 'always',
      animatedZooms: true,
      title: 'dygraphs chart template',
      connectSeparatedPoints: true,
      legendFormatter: function(data) {
        return data.series.map(element => {
            return `<span style="font-weight:bold; color:${element.color};"><div class="dygraph-legend-line"></div> ${element.labelHTML}: ${element.yHTML || '-'}</span>`;
        }).join('<br/>');
      }
    });`

You can see it in action here:
https://jsfiddle.net/6q3wkna4/

**Comment by mirabilos** [comment] 2023-02-17 00:28
PR was merged

**Closed by mirabilos** 2023-02-17 00:28 UTC
Labels: bug
