### ISSUE TITLE
Graph renders smaller and out of place after update

### ISSUE THREAD

**Issue by cotrina** [danvk/dygraphs#827] opened 2017-01-17 18:47 UTC
I've been using dygraphs for 4 years without this issue then all of the sudden 2 months ago my graph started to exhibit a bug where the graph renders smaller over the original graph. When I try and zoom in only the smaller graph responds. 

![dygraph issue](https://cloud.githubusercontent.com/assets/13260060/22033971/7c1dc5a0-dc9f-11e6-8e4b-dfa8bdc293b3.jpg)

I've updated my dygraph library to version 2.0 and started using the dygraph css files but the issues still occurs. The issues seems to happen when my I push an update to my data set while my browser tab is out of focus.

The update function I use is
```
data.push([x,a,b]);								
g.updateOptions({'file':data});
```

I'm using the latest version of chrome. 

My data array looks like this:

```
var data = [
[new Date("2017/01/01 10:24:00"),10000,11000],
[new Date("2017/01/01 10:26:00"),10004,11002]
 ];
```

This is the js for my graph:

```
var g = new Dygraph(
 document.getElementById("activegraph"),
 data,
  {
	labels: [ "Date", "Active","Combined"],
 	colors: ['#53868B','#000000'], 					
	showRoller: true,
	logscale: false,
	strokeWidth:1.5,
	xRangePad:10,
	customBars: false,
	axisLabelFontSize: 13,   
	highlightCircleSize: 4,
	legend: 'always',
	visibility: [true, true],
	labelsDiv: document.getElementById("active_labels"),
	labelsDivWidth: 300      
}
);
```

**Comment by danvk** [comment] 2017-01-17 19:31
Are you including the dygraphs CSS file?

**Comment by danvk** [comment] 2017-01-17 19:32
Can you share a full example, preferably using something like dygraphs.com/fiddle?

**Comment by cotrina** [comment] 2017-01-17 19:42
Sure. Let me throw something together.

**Comment by danvk** [comment] 2017-01-17 19:43
Thanks. Just based on your description, it sounds likely that this was broken by the CSS change https://github.com/danvk/dygraphs/pull/678

**Comment by Y-Selim** [comment] 2017-01-17 20:24
Duplicate of #810

**Comment by cotrina** [comment] 2017-01-18 22:10
I was able to replicate here: http://jsfiddle.net/eM2Mg/9219/

Seems to happen when I'm on another tab in the same browser window. 

![dygraph](https://cloud.githubusercontent.com/assets/13260060/22085130/9c4c85b2-dd87-11e6-9abf-4bccdb1f9f1c.jpg)

**Comment by danvk** [comment] 2017-01-18 23:28
You're sourcing dygraphs 1.1.1. there, right? (`dygraph-dev.js`)

**Comment by cotrina** [comment] 2017-01-18 23:37
Sorry I did not realize that I was. Updated to 2.0 below, same issue. 

http://jsfiddle.net/eM2Mg/9220/

![untitled](https://cloud.githubusercontent.com/assets/13260060/22087640/e2895404-dd93-11e6-920e-82acb279524e.jpg)

**Comment by dp2648** [comment] 2017-04-19 11:21
Any updates on this? 
I too faced this issue on Chrome Version 56.0.2924.87 (64-bit)

**Comment by darcyparker** [comment] 2017-06-19 21:08
In case it helps others.  I had a similiar problem and worked around it with code roughly like this:

(Perhaps this snippet will help others and maybe it can be used to create a pull request to fix this issue.)

```javascript
    public update(...): Promise<void> {
        //promise blocks update until page is visible again
        //if update() is called an additional time before the page is visible, the promise is superseded.
        //So this.graph.update() is only made for the last call to this.update() while the page was hidden.
        if (window.document.hidden) {
            if (this.rejectReadyToUpdatePromise !== undefined) {
                //reject the previous readyToUpdatePromise promise
                if (this.visibilityChangeHandler !== undefined && this.visibilityChangeHandler !== null) {
                    window.removeEventListener('visibilitychange', this.visibilityChangeHandler);
                    delete this.visibilityChangeHandler;
                }
                this.rejectReadyToUpdatePromise(READYTOUPDATESUPERCEEDED);
                delete this.rejectReadyToUpdatePromise;
                delete this.resolveReadyToUpdatePromise;
            }
            return this.readyToUpdatePromise = new Promise<void>((resolve, reject) => {
                    this.resolveReadyToUpdatePromise = resolve;
                    this.rejectReadyToUpdatePromise = reject;
                    this.visibilityChangeHandler = () => {
                        if (window.document.visibilityState === 'visible') {
                            this.resolveReadyToUpdatePromise();
                            delete this.rejectReadyToUpdatePromise;
                            delete this.resolveReadyToUpdatePromise;
                            if (this.visibilityChangeHandler !== undefined) {
                                this.$window.removeEventListener('visibilitychange', this.visibilityChangeHandler);
                                delete this.visibilityChangeHandler;
                            }

                        }
                    };
                    this.$window.addEventListener('visibilitychange', this.visibilityChangeHandler);
                })
                .catch(error => {
                    if (error === READYTOUPDATESUPERCEEDED) {
                        return this.readyToUpdatePromise; //superceeded with latest promise
                    }
                    return Promise.reject(error);
                })
                .then(() => { this.update(...) }) //recall update when page is not visible
        } else {
            //update can proceed because page is visible...
            this.graph.updateOptions(...);
            return Promise.resolve();
        }
    }
```

**Comment by pshevtsov** [comment] 2017-10-25 10:56
@cotrina Your fiddle lacks CSS. Here's the updated one with CSS included: http://jsfiddle.net/eM2Mg/10571/

**Closed by pshevtsov** 2017-10-25 10:56 UTC
