### ISSUE TITLE
Range selector shows buggy grid when g.updateOptions({ showRangeSelector: true }); is set

### ISSUE THREAD

**Issue by taismi** [danvk/dygraphs#768] opened 2016-08-21 12:00 UTC
Range selector shows buggy grid when g.updateOptions({ showRangeSelector: true }); is set.

The bug can been seen is this example. http://jsfiddle.net/v2dkxnee/

![range_selector_bug](https://cloud.githubusercontent.com/assets/16210105/17837011/f3519152-67af-11e6-9cc7-850a3da2a0c5.png)

**Comment by danvk** [comment] 2016-08-25 14:07
Toggling `showRangeSelector` via `updateOptions` isn't supported. Dupe of #360

**Closed by danvk** 2016-08-25 14:07 UTC
